// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GeneralToolsRandomTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void generalToolsRandom() {
    driver.get("http://localhost:8080/Login");
    driver.manage().window().setSize(new Dimension(639, 831));
    driver.findElement(By.id("TestLoginLink_button")).click();
    driver.findElement(By.cssSelector(".btn > .glyphicon-wrench")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(6)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("0"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-default:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Auto Screens")).click();
    driver.findElement(By.id("EntityList_aen_0_find")).click();
    driver.findElement(By.id("FindValueDialog-button")).click();
    driver.findElement(By.name("billingAccountId_not")).click();
    driver.findElement(By.name("billFromPartyId_not")).click();
    driver.findElement(By.id("FindEntityValue_submitButton")).click();
    driver.findElement(By.id("CreateValueDialog-button")).click();
    driver.findElement(By.cssSelector("#CreateEntityValue_thruDate .glyphicon")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > .day:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".glyphicon-remove")).click();
    driver.findElement(By.id("CreateEntityValue_submitButton")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-default:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-default:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("form > .btn")).click();
    driver.findElement(By.id("EntityList_aen_95_find")).click();
    driver.findElement(By.cssSelector("th:nth-child(3) .glyphicon-triangle-bottom")).click();
    driver.findElement(By.cssSelector("th:nth-child(3) .glyphicon-triangle-top")).click();
    driver.findElement(By.cssSelector("th:nth-child(4) .glyphicon-triangle-bottom")).click();
    driver.findElement(By.id("ListEntityValue_hdialog_button")).click();
    driver.findElement(By.name("clearParameters")).click();
    driver.findElement(By.linkText("Tools")).click();
    driver.findElement(By.linkText("Dashboard")).click();
    driver.findElement(By.linkText("Artifact Stats")).click();
    driver.findElement(By.linkText("Tools")).click();
    driver.findElement(By.linkText("Service")).click();
    driver.findElement(By.id("ServiceList_detail_0_serviceDetail")).click();
    driver.findElement(By.linkText("Service List")).click();
    driver.findElement(By.cssSelector(".form-list-nav-row:nth-child(41) .glyphicon-fast-forward")).click();
    driver.findElement(By.id("ServiceList_detail_5_serviceDetail")).click();
    driver.findElement(By.linkText("Site Map")).click();
    {
      WebElement element = driver.findElement(By.linkText("Built on Moqui Framework 3.0.0-rc2"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Audit Log")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("EntityAuditLogList_hdialog_button")).click();
    driver.findElement(By.cssSelector(".fa")).click();
    driver.findElement(By.name("changedEntityName_ic")).click();
    driver.findElement(By.name("changedFieldName_ic")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(8) span:nth-child(5)")).click();
    driver.findElement(By.name("oldValueText_ic")).click();
    driver.findElement(By.name("changedInVisitId_ic")).click();
    driver.findElement(By.id("EntityAuditLogList_header_find")).click();
    driver.findElement(By.linkText("Site Map")).click();
    driver.findElement(By.cssSelector(".ScreenTreeNested:nth-child(4) > .ScreenTreeNested:nth-child(8) > a:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("Thread List")).click();
    driver.findElement(By.cssSelector("#ThreadList_SelColsDialog_button > .glyphicon")).click();
    driver.findElement(By.name("SaveColumns")).click();
    driver.findElement(By.id("SetWorkerPoolDialog-button")).click();
    driver.findElement(By.id("SetWorkerPoolForm_coreSize")).click();
    driver.findElement(By.id("SetWorkerPoolForm_coreSize")).sendKeys("24");
    driver.findElement(By.id("SetWorkerPoolForm_submitButton")).click();
    driver.findElement(By.linkText("Site Map")).click();
    driver.findElement(By.linkText("Cache")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("CacheList_name_0_cacheElements")).click();
    driver.findElement(By.linkText("Site Map")).click();
    driver.findElement(By.linkText("Tools")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("SQL Runner")).click();
    driver.findElement(By.id("SqlOptions_sql")).click();
    driver.findElement(By.id("select2-SqlOptions_groupName-container")).click();
    driver.findElement(By.id("SqlOptions_limit")).sendKeys("300");
    driver.findElement(By.id("SqlOptions_limit")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("SqlOptions_limit")).click();
    driver.findElement(By.cssSelector(".form-horizontal")).click();
    driver.findElement(By.id("SqlOptions_sql")).click();
    driver.findElement(By.id("SqlOptions_submitButton")).click();
    driver.findElement(By.id("SqlOptions_submitButton")).click();
    driver.findElement(By.cssSelector("p:nth-child(2)")).click();
    driver.findElement(By.linkText("Site Map")).click();
    driver.findElement(By.cssSelector(".ScreenTreeNested:nth-child(4) > .ScreenTreeNested:nth-child(10) > a:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("Data Snapshots")).click();
    driver.findElement(By.id("ExportDialog-button")).click();
    driver.findElement(By.cssSelector(".select2-search__field")).click();
    driver.findElement(By.cssSelector("#ExportData .form-group:nth-child(1) > .control-label")).click();
    driver.findElement(By.id("ExportData_fromDate_idate")).click();
    driver.findElement(By.cssSelector("#ExportData_fromDate > .input-group-addon")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > .day:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".glyphicon-remove")).click();
    driver.findElement(By.cssSelector("#ExportData_thruDate .glyphicon")).click();
    driver.findElement(By.cssSelector("tr:nth-child(6) > .day:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".input-group-addon:nth-child(3) > .glyphicon")).click();
    driver.findElement(By.id("ExportData_baseFilename")).click();
    driver.findElement(By.linkText("Site Map")).click();
    driver.findElement(By.linkText("Speed Test")).click();
    driver.findElement(By.id("SelectBaseCalls_submitButton")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) .GStringImpl")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) .GStringImpl")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(1) .GStringImpl"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("tr:nth-child(1) .GStringImpl")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) .GStringImpl")).click();
    driver.findElement(By.id("SelectBaseCalls_submitButton")).click();
    driver.findElement(By.linkText("Site Map")).click();
    driver.findElement(By.linkText("Query Stats")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("th:nth-child(1) > div:nth-child(1) .glyphicon-triangle-top")).click();
    driver.findElement(By.cssSelector("th:nth-child(1) > div:nth-child(1) .glyphicon-triangle-bottom")).click();
    driver.findElement(By.cssSelector("th:nth-child(1) > div:nth-child(2) .glyphicon-triangle-top")).click();
    driver.findElement(By.cssSelector("tbody")).click();
    driver.findElement(By.linkText("Site Map")).click();
    driver.findElement(By.linkText("Tools")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-danger"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".glyphicon-off")).click();
  }
}
