// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("http://localhost:8080/Login");
    driver.manage().window().setSize(new Dimension(639, 831));
    driver.findElement(By.id("TestLoginLink_button")).click();
    driver.get("http://localhost:8080/vapps");
    WebElement firstResult = new WebDriverWait(driver, Duration.ofSeconds(10).getSeconds())
            .until(ExpectedConditions.elementToBeClickable(By.linkText("Tools")));
    driver.findElement(By.linkText("Tools")).click();
    driver.findElement(By.linkText("Auto Screens")).click();
    driver.findElement(By.id("EntityList_aen_0_find")).click();
    driver.findElement(By.cssSelector("form > .btn")).click();
  }
}
